### ISSUE TITLE
Feature Request: Test against last patch versions only

### ISSUE THREAD

**Issue by grv87** [ajoberstar/gradle-stutter#17]
It would be good to have an option to test against last patch versions only.
For example, I declare:
```
compatibleRange '4.9'
```
For now, there are the following Gradle versions: `4.9`, `4.10`, `4.10.1`, `4.10.2`.
`4.10.1` and `4.10.2` are bug fixes for `4.10`.

I would like to test against last patch version for each minor, i.e. `4.9` and `4.10.2` only.
I don't see a reason to support `4.10` and `4.10.1` and test against them:
1. If my plugin works with `4.9` and `4.10.2`, it is safe to assume that it works with `4.10` and `4.10.1` too, or `4.10` and `4.10.1` contain bugs and are not supported.
2. It is not a problem for a user to update Gradle to next patch release.
3. It is just another way to limit number of versions tested. For me, `sparse` seems to overly limit number of versions. I had problems with incompatibilities between minor versions in the past, so I would like to test against each minor. But not against each patch.

Right now this is impossible without manual coding.

**Comment by ajoberstar** [comment]
[0.5.0-rc-1](https://github.com/ajoberstar/gradle-stutter/releases/tag/0.5.0-rc.1) includes this behavior, if you want to give it a try.
