### ISSUE TITLE
Disable compatibility testing with other Gradle versions from command line

### ISSUE THREAD

**Issue by szpak** [ajoberstar/gradle-stutter#22]
`check` by default depends on `compatTest`. With local development I would like to run `compatTest`s only with the current Gradle version leaving more thoroughgoing testing for CI (or for running them on demand after bigger changes). I cannot easily skip `compatTest` as my sanity tests defined there would not be executed at all. It is required to conditionally set `compatibilityRange` which is not elegant.

It would be useful to have a property in the extension to be able set in my `build.gradle` to indicate that `compatTest` should be only executed for the current Gradle version (false by default).

**Comment by ajoberstar** [comment]
So you want to be able to run `check` but only have it depend on the current Gradle version, rather than everything you're compatible with? (But only locally)

**Comment by szpak** [comment]
That's the main case. However, in general something else could also depend on `compatTest` in my project. Therefore, I would say that in that mode (explicitly enabled by a change in the project configuration or from the command line which changes the configuration) `compatTest` should only be execute for the current Gradle version. I might want to put in my `~/.gradle/gradle.properties` something to execute `check`/`compatTest` in the short mode to have more throughout testing on CI (or on demand locally `-P...` having some ongoing bigger changes in API).

**Comment by szpak** [comment]
An another case. Currently, I have repression tests with Java 8 on the CI server. I would like to be able to run also tests with Java 11 and 14 with just current Gradle version (to speed it up). To achieve that, I have to replace the content of the lock files before Gradle execution which is somehow fragile.

**Comment by ajoberstar** [comment]
@szpak I just release [0.7.0](https://github.com/ajoberstar/gradle-stutter/releases/tag/0.7.0) which has a major change to supporting matrices with Java versions (leveraging Gradle's toolchain feature). Also leaving the configuration of whether and how to wire a dependency from the `check` task up to the author, I think this might give you the flexibility you wanted.

Let me know if you have feedback on this new version.

**Comment by ajoberstar** [comment]
Closing under the assumption this is resolved. If that's not true and you want to discuss further, please reopen.
